type Query {
    movies: [Movie!]!
    movie(id: ID!): Movie
    searchMovies(title: String!): [Movie]
    people: [Person!]!
    moviesByIds(ids: [ID!]!): [Movie]
}

enum Genre {
    ACTION
    ANIMATION
    COMEDY
    CRIME
    DOCUMENTARY
    DRAMA
    FANTASY
    HORROR
    MUSICAL
    MYSTERY
    ROMANCE
    SCIFI
    THRILLER
    WAR
    WESTERN
}

type Movie {
    id: ID!
    title: String!
    releaseYear: Int!
    genre: Genre
    rating: Float
    directors: [Person!]!
    cast: [MovieCast!]!
}

type Person {
    id: ID!
    name: String!
    birthYear: Int
    nationality: String
}

type MovieCast {
    id: ID!
    characterName: String!
    person: Person!
}

type AuthResponse {
    token: String!
    user: User!
}

type User {
    id: ID!
    username: String!
    email: String!
    role: Role!
}

enum Role {
    USER,
    ADMIN
}

type Mutation {
    deleteMovie(id: ID!): DeleteMovieResponse!
    createPerson(input: CreatePersonInput!): Person!
    updatePerson(input: UpdatePersonInput!): Person!
    deletePerson(id: ID!): DeletePersonResponse!
    login(input: LoginInput!): AuthResponse!
}

input LoginInput {
    username: String!
    password: String!
}

input UpdatePersonInput {
    id: ID!
    name: String
    birthYear: Int
    nationality: String
}

input CreatePersonInput {
    name: String!
    birthYear: Int
    nationality: String
}

type DeleteMovieResponse {
    success: Boolean!
    message: String!
    deletedId: String
}

type DeletePersonResponse {
    success: Boolean!
    error: DeletePersonError
    deletedId: String
}

enum DeletePersonError {
    LINKED_TO_MOVIE
}
