type Query {
    movies: [Movie!]!
    movie(id: ID!): Movie
    searchMovies(title: String!): [Movie]
}

enum Genre {
    ACTION
    ANIMATION
    COMEDY
    CRIME
    DOCUMENTARY
    DRAMA
    FANTASY
    HORROR
    MUSICAL
    MYSTERY
    ROMANCE
    SCIFI
    THRILLER
    WAR
    WESTERN
}

type Movie {
    id: ID!
    title: String!
    releaseYear: Int!
    genre: Genre
    rating: Float
    directors: [Person!]!
    cast: [MovieCast!]!
}

type Person {
    id: ID!
    name: String!
    birthYear: Int
    nationality: String
}

type MovieCast {
    id: ID!
    characterName: String!
    person: Person!
}